# Generated by Django 2.0.6 on 2018-06-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_word',
            new_name='word_book',
        ),
    ]
