# Generated by Django 2.0.6 on 2018-06-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180630_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
